image: wmacmillan/gp-general-dev

ports:
- port: 8050
  onOpen: ignore
- port: 8888
  onOpen: ignore

tasks:
- command: pip install shortuuid matplotlib pyex quantstats && nohup jupyter notebook pyex --config=/workspace/quant-coding-test/.jupyter/jupyter_notebook_config.py


github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: false
    addBadge: true

vscode:
  extensions:
    - ms-python.python
    - njpwerner.autodocstring
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
